---
# Configure jenkins

- name: service is enabled and started
  service:
    name: "{{ item }}"
    enabled: true
    state: started
  become: true
  loop: "{{ jenkins_services_enable }}"
  when: jenkins_enable_service
