---
# Retrieve password

- name: retrieve and display initial admin password
  block:
    - name: retrieve initial jenkins password
      slurp:
        src: /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_password
      become: true

    - name: display initial jenkins password
      debug:
        msg: "Initial jenkins admin password: {{ jenkins_password['content'] | b64decode }}"
  rescue:
    - debug:
        msg: "Cannot display initialAdminPassword: file not found."
